---
:backends: yaml
:yaml:
  :datadir: "/puppet/environments/%{::environment}/manifests/configuration"
:hierarchy:
  - "%{::clientcert}"
  - "%{::environment}"
  - "virtual_%{::is_virtual}"
  - common
:logger: console
